### ISSUE TITLE
stof_doctrine_extensions default locale

### ISSUE THREAD

**Issue by Mopster** [KunstmaanLegacy/KunstmaanSandbox#79]
In the config.dist.yml the default_locale for stof_doctrine_extensions is set to nl : 

``` yml
stof_doctrine_extensions:
    default_locale: nl
    translation_fallback: true
    orm:
        default:
           loggable: true
           translatable: true
           sluggable: true
```

Since we set the default locale to 'en' in our parameters.yml, shouldn't it be 'en' here too ?
